# Generated by Django 4.2.3 on 2023-07-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PHC',
            fields=[
                ('phc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phc_name', models.CharField(max_length=100, null=True)),
                ('summary', models.CharField(max_length=3000, null=True)),
                ('password', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('no_of_beds', models.IntegerField()),
                ('gmap_link', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
