# Generated by Django 4.2.3 on 2023-07-16 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medician',
            fields=[
                ('medician_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('medician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part2.medician')),
                ('phc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part2.phc')),
            ],
        ),
    ]
