# Generated by Django 4.2.3 on 2023-07-16 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part2', '0002_medician_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='immunisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('vaccine_name', models.CharField(max_length=50)),
                ('no_of_vaccines', models.IntegerField()),
                ('phc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part2.phc')),
            ],
        ),
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.IntegerField()),
                ('patient_name', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=11, null=True)),
                ('guardian_name', models.CharField(max_length=50, null=True)),
                ('street', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('blood_group', models.CharField(max_length=4, null=True)),
                ('cause', models.CharField(max_length=50)),
                ('admission_time', models.DateTimeField(auto_now_add=True)),
                ('discharge_time', models.DateTimeField(null=True)),
                ('discharge_status', models.CharField(max_length=50)),
                ('report', models.FileField(null=True, upload_to='pdf')),
                ('phc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part2.phc')),
            ],
        ),
    ]
